// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

import "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/**
 * @title RevenueSplitter
 * @dev Automatic 70/30 revenue split for template subscriptions
 * @notice Varity receives 70%, template creators receive 30%
 *
 * Security Features:
 * - ReentrancyGuard on all payment functions
 * - Pull payment pattern for creator withdrawals
 * - SafeERC20 for stablecoin transfers
 * - Emergency pause functionality
 * - Comprehensive event logging for transparency
 */
contract RevenueSplitter is
    Initializable,
    AccessControlUpgradeable,
    ReentrancyGuardUpgradeable,
    UUPSUpgradeable
{
    using SafeERC20 for IERC20;

    /// @dev Role for marketplace contract to process payments
    bytes32 public constant MARKETPLACE_ROLE = keccak256("MARKETPLACE_ROLE");

    /// @dev Role for authorized upgraders
    bytes32 public constant UPGRADER_ROLE = keccak256("UPGRADER_ROLE");

    /// @dev Varity platform percentage (70%)
    uint256 public constant VARITY_PERCENTAGE = 70;

    /// @dev Template creator percentage (30%)
    uint256 public constant CREATOR_PERCENTAGE = 30;

    /// @dev Basis points for precise percentage calculations
    uint256 private constant BASIS_POINTS = 100;

    /// @dev Varity treasury address (receives 70% of all revenue)
    address public varietyTreasury;

    /**
     * @dev Revenue split tracking structure
     * @param creator Address of template creator
     * @param totalRevenue Total revenue generated by this template
     * @param varietyShare Total amount sent to Varity treasury
     * @param creatorShare Total amount allocated to creator
     * @param lastPaymentTimestamp Timestamp of most recent payment
     */
    struct RevenueSplit {
        address creator;
        uint256 totalRevenue;
        uint256 varietyShare;
        uint256 creatorShare;
        uint256 lastPaymentTimestamp;
    }

    /// @dev Mapping from templateId to revenue split data
    mapping(uint256 => RevenueSplit) public splits;

    /// @dev Mapping from creator address to pending ETH withdrawals
    mapping(address => uint256) public pendingWithdrawals;

    /// @dev Mapping from creator address to token address to pending token withdrawals
    mapping(address => mapping(address => uint256)) public pendingTokenWithdrawals;

    /// @dev Whitelisted stablecoins for payment
    mapping(address => bool) public whitelistedTokens;

    /// @dev Emergency pause flag
    bool public paused;

    // Custom errors
    error InsufficientPayment(uint256 required, uint256 provided);
    error TransferFailed(address recipient, uint256 amount);
    error NoPendingWithdrawals(address creator);
    error ContractPaused();
    error InvalidTreasuryAddress();
    error TokenNotWhitelisted(address token);
    error InvalidAmount(uint256 amount);

    // Events
    event PaymentProcessed(
        uint256 indexed templateId,
        address indexed creator,
        uint256 totalAmount,
        uint256 varietyShare,
        uint256 creatorShare,
        uint256 timestamp
    );

    event StablecoinPaymentProcessed(
        uint256 indexed templateId,
        address indexed creator,
        address indexed token,
        uint256 totalAmount,
        uint256 varietyShare,
        uint256 creatorShare,
        uint256 timestamp
    );

    event WithdrawalProcessed(
        address indexed creator,
        uint256 amount,
        uint256 timestamp
    );

    event TokenWithdrawalProcessed(
        address indexed creator,
        address indexed token,
        uint256 amount,
        uint256 timestamp
    );

    event TreasuryUpdated(
        address indexed oldTreasury,
        address indexed newTreasury,
        uint256 timestamp
    );

    event TokenWhitelisted(
        address indexed token,
        bool whitelisted,
        uint256 timestamp
    );

    event PauseToggled(bool paused, uint256 timestamp);

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    /**
     * @dev Initializes the contract
     * @param _varietyTreasury Address of Varity treasury
     * @param _admin Address to be granted admin role
     */
    function initialize(
        address _varietyTreasury,
        address _admin
    ) public initializer {
        if (_varietyTreasury == address(0)) revert InvalidTreasuryAddress();

        __AccessControl_init();
        __ReentrancyGuard_init();
        __UUPSUpgradeable_init();

        varietyTreasury = _varietyTreasury;

        _grantRole(DEFAULT_ADMIN_ROLE, _admin);
        _grantRole(MARKETPLACE_ROLE, _admin);
        _grantRole(UPGRADER_ROLE, _admin);

        paused = false;
    }

    /**
     * @dev Process ETH payment and split revenue 70/30
     * @param templateId Template NFT ID
     * @param creator Template creator address
     * @param amount Payment amount in wei
     *
     * Requirements:
     * - Contract must not be paused
     * - msg.value must equal amount
     * - Caller must have MARKETPLACE_ROLE
     */
    function processPayment(
        uint256 templateId,
        address creator,
        uint256 amount
    ) external payable onlyRole(MARKETPLACE_ROLE) nonReentrant {
        if (paused) revert ContractPaused();
        if (msg.value != amount) revert InsufficientPayment(amount, msg.value);
        if (amount == 0) revert InvalidAmount(amount);

        // Calculate splits
        uint256 varietyShare = (amount * VARITY_PERCENTAGE) / BASIS_POINTS;
        uint256 creatorShare = amount - varietyShare;

        // Update split tracking
        RevenueSplit storage split = splits[templateId];
        split.creator = creator;
        split.totalRevenue += amount;
        split.varietyShare += varietyShare;
        split.creatorShare += creatorShare;
        split.lastPaymentTimestamp = block.timestamp;

        // Send Varity share immediately to treasury
        (bool varietySuccess, ) = varietyTreasury.call{value: varietyShare}("");
        if (!varietySuccess) revert TransferFailed(varietyTreasury, varietyShare);

        // Add creator share to pending withdrawals (pull pattern for security)
        pendingWithdrawals[creator] += creatorShare;

        emit PaymentProcessed(
            templateId,
            creator,
            amount,
            varietyShare,
            creatorShare,
            block.timestamp
        );
    }

    /**
     * @dev Process stablecoin payment (USDC, USDT, DAI)
     * @param templateId Template NFT ID
     * @param creator Template creator address
     * @param token Stablecoin contract address
     * @param amount Payment amount in token units
     *
     * Requirements:
     * - Contract must not be paused
     * - Token must be whitelisted
     * - Caller must have approved this contract to spend tokens
     * - Caller must have MARKETPLACE_ROLE
     */
    function processStablecoinPayment(
        uint256 templateId,
        address creator,
        address token,
        uint256 amount
    ) external onlyRole(MARKETPLACE_ROLE) nonReentrant {
        if (paused) revert ContractPaused();
        if (!whitelistedTokens[token]) revert TokenNotWhitelisted(token);
        if (amount == 0) revert InvalidAmount(amount);

        IERC20 stablecoin = IERC20(token);

        // Transfer tokens from marketplace to this contract
        stablecoin.safeTransferFrom(msg.sender, address(this), amount);

        // Calculate splits
        uint256 varietyShare = (amount * VARITY_PERCENTAGE) / BASIS_POINTS;
        uint256 creatorShare = amount - varietyShare;

        // Update split tracking
        RevenueSplit storage split = splits[templateId];
        split.creator = creator;
        split.totalRevenue += amount;
        split.varietyShare += varietyShare;
        split.creatorShare += creatorShare;
        split.lastPaymentTimestamp = block.timestamp;

        // Transfer Varity share immediately to treasury
        stablecoin.safeTransfer(varietyTreasury, varietyShare);

        // Add creator share to pending token withdrawals (pull pattern)
        pendingTokenWithdrawals[creator][token] += creatorShare;

        emit StablecoinPaymentProcessed(
            templateId,
            creator,
            token,
            amount,
            varietyShare,
            creatorShare,
            block.timestamp
        );
    }

    /**
     * @dev Creators withdraw pending ETH payments
     *
     * Requirements:
     * - Caller must have pending withdrawals
     * - Contract must not be paused
     */
    function withdrawPending() external nonReentrant {
        if (paused) revert ContractPaused();

        uint256 amount = pendingWithdrawals[msg.sender];
        if (amount == 0) revert NoPendingWithdrawals(msg.sender);

        // Reset pending withdrawals before transfer (Checks-Effects-Interactions)
        pendingWithdrawals[msg.sender] = 0;

        // Transfer ETH to creator
        (bool success, ) = msg.sender.call{value: amount}("");
        if (!success) revert TransferFailed(msg.sender, amount);

        emit WithdrawalProcessed(msg.sender, amount, block.timestamp);
    }

    /**
     * @dev Creators withdraw pending token payments
     * @param token Stablecoin contract address
     *
     * Requirements:
     * - Caller must have pending token withdrawals
     * - Contract must not be paused
     */
    function withdrawPendingTokens(address token) external nonReentrant {
        if (paused) revert ContractPaused();

        uint256 amount = pendingTokenWithdrawals[msg.sender][token];
        if (amount == 0) revert NoPendingWithdrawals(msg.sender);

        // Reset pending withdrawals before transfer (Checks-Effects-Interactions)
        pendingTokenWithdrawals[msg.sender][token] = 0;

        // Transfer tokens to creator
        IERC20(token).safeTransfer(msg.sender, amount);

        emit TokenWithdrawalProcessed(msg.sender, token, amount, block.timestamp);
    }

    /**
     * @dev Update Varity treasury address
     * @param newTreasury New treasury address
     *
     * Requirements:
     * - Caller must have DEFAULT_ADMIN_ROLE
     */
    function updateTreasury(address newTreasury)
        external
        onlyRole(DEFAULT_ADMIN_ROLE)
    {
        if (newTreasury == address(0)) revert InvalidTreasuryAddress();

        address oldTreasury = varietyTreasury;
        varietyTreasury = newTreasury;

        emit TreasuryUpdated(oldTreasury, newTreasury, block.timestamp);
    }

    /**
     * @dev Whitelist or remove a stablecoin token
     * @param token Token contract address
     * @param whitelisted Whether to whitelist or remove
     *
     * Requirements:
     * - Caller must have DEFAULT_ADMIN_ROLE
     */
    function setTokenWhitelist(address token, bool whitelisted)
        external
        onlyRole(DEFAULT_ADMIN_ROLE)
    {
        whitelistedTokens[token] = whitelisted;
        emit TokenWhitelisted(token, whitelisted, block.timestamp);
    }

    /**
     * @dev Toggle pause state
     *
     * Requirements:
     * - Caller must have DEFAULT_ADMIN_ROLE
     */
    function togglePause() external onlyRole(DEFAULT_ADMIN_ROLE) {
        paused = !paused;
        emit PauseToggled(paused, block.timestamp);
    }

    /**
     * @dev Get revenue split details for a template
     * @param templateId Template NFT ID
     * @return split Complete revenue split structure
     */
    function getRevenueSplit(uint256 templateId)
        external
        view
        returns (RevenueSplit memory)
    {
        return splits[templateId];
    }

    /**
     * @dev Get pending ETH withdrawal amount for a creator
     * @param creator Creator address
     * @return amount Pending withdrawal amount in wei
     */
    function getPendingWithdrawal(address creator)
        external
        view
        returns (uint256)
    {
        return pendingWithdrawals[creator];
    }

    /**
     * @dev Get pending token withdrawal amount for a creator
     * @param creator Creator address
     * @param token Token contract address
     * @return amount Pending token withdrawal amount
     */
    function getPendingTokenWithdrawal(address creator, address token)
        external
        view
        returns (uint256)
    {
        return pendingTokenWithdrawals[creator][token];
    }

    /**
     * @dev Required override for UUPS upgradeability
     */
    function _authorizeUpgrade(address newImplementation)
        internal
        override
        onlyRole(UPGRADER_ROLE)
    {}

    /**
     * @dev Receive function to accept ETH
     */
    receive() external payable {}
}
