/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ToolMarketplace {
  export type ToolListingStruct = {
    toolId: BigNumberish;
    developer: AddressLike;
    isActive: boolean;
    totalSales: BigNumberish;
    rating: BigNumberish;
    reviewCount: BigNumberish;
  };

  export type ToolListingStructOutput = [
    toolId: bigint,
    developer: string,
    isActive: boolean,
    totalSales: bigint,
    rating: bigint,
    reviewCount: bigint
  ] & {
    toolId: bigint;
    developer: string;
    isActive: boolean;
    totalSales: bigint;
    rating: bigint;
    reviewCount: bigint;
  };

  export type ReviewStruct = {
    reviewer: AddressLike;
    toolId: BigNumberish;
    rating: BigNumberish;
    comment: string;
    timestamp: BigNumberish;
  };

  export type ReviewStructOutput = [
    reviewer: string,
    toolId: bigint,
    rating: bigint,
    comment: string,
    timestamp: bigint
  ] & {
    reviewer: string;
    toolId: bigint;
    rating: bigint;
    comment: string;
    timestamp: bigint;
  };
}

export interface ToolMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_RATING"
      | "MIN_RATING"
      | "UPGRADER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "getActiveTools"
      | "getReviewCount"
      | "getRoleAdmin"
      | "getToolListing"
      | "getToolReviews"
      | "grantRole"
      | "hasReviewed"
      | "hasRole"
      | "initialize"
      | "leaveReview"
      | "listTool"
      | "listings"
      | "platformFee"
      | "proxiableUUID"
      | "purchaseLicense"
      | "renounceRole"
      | "revenueSplitter"
      | "revokeRole"
      | "subscriptionBilling"
      | "supportsInterface"
      | "toggleToolStatus"
      | "toolLicenseNFT"
      | "totalToolsListed"
      | "updatePlatformFee"
      | "updateUsdcToken"
      | "upgradeToAndCall"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "LicensePurchased"
      | "PlatformFeeUpdated"
      | "ReviewSubmitted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ToolListed"
      | "ToolStatusUpdated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RATING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_RATING",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveTools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getToolListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getToolReviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaveReview",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "listTool",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseLicense",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revenueSplitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionBilling",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleToolStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toolLicenseNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalToolsListed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUsdcToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_RATING", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_RATING", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveTools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReviewCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getToolListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getToolReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leaveReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listTool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueSplitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionBilling",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleToolStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toolLicenseNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalToolsListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUsdcToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicensePurchasedEvent {
  export type InputTuple = [
    customer: AddressLike,
    toolId: BigNumberish,
    durationMonths: BigNumberish,
    totalCost: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    customer: string,
    toolId: bigint,
    durationMonths: bigint,
    totalCost: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    customer: string;
    toolId: bigint;
    durationMonths: bigint;
    totalCost: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [
    oldFee: BigNumberish,
    newFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [oldFee: bigint, newFee: bigint, timestamp: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    toolId: BigNumberish,
    reviewer: AddressLike,
    rating: BigNumberish,
    comment: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    toolId: bigint,
    reviewer: string,
    rating: bigint,
    comment: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    toolId: bigint;
    reviewer: string;
    rating: bigint;
    comment: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolListedEvent {
  export type InputTuple = [
    toolId: BigNumberish,
    developer: AddressLike,
    name: string,
    category: string,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    toolId: bigint,
    developer: string,
    name: string,
    category: string,
    price: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    toolId: bigint;
    developer: string;
    name: string;
    category: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ToolStatusUpdatedEvent {
  export type InputTuple = [
    toolId: BigNumberish,
    isActive: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    toolId: bigint,
    isActive: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    toolId: bigint;
    isActive: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ToolMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): ToolMarketplace;
  waitForDeployment(): Promise<this>;

  interface: ToolMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_RATING: TypedContractMethod<[], [bigint], "view">;

  MIN_RATING: TypedContractMethod<[], [bigint], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  getActiveTools: TypedContractMethod<[], [bigint[]], "view">;

  getReviewCount: TypedContractMethod<[toolId: BigNumberish], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getToolListing: TypedContractMethod<
    [toolId: BigNumberish],
    [ToolMarketplace.ToolListingStructOutput],
    "view"
  >;

  getToolReviews: TypedContractMethod<
    [toolId: BigNumberish],
    [ToolMarketplace.ReviewStructOutput[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasReviewed: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _toolLicenseNFT: AddressLike,
      _revenueSplitter: AddressLike,
      _subscriptionBilling: AddressLike,
      _usdcToken: AddressLike,
      _admin: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  leaveReview: TypedContractMethod<
    [toolId: BigNumberish, rating: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;

  listTool: TypedContractMethod<
    [
      name: string,
      category: string,
      monthlyPrice: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, bigint, bigint, bigint] & {
        toolId: bigint;
        developer: string;
        isActive: boolean;
        totalSales: bigint;
        rating: bigint;
        reviewCount: bigint;
      }
    ],
    "view"
  >;

  platformFee: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  purchaseLicense: TypedContractMethod<
    [toolId: BigNumberish, durationMonths: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revenueSplitter: TypedContractMethod<[], [string], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  subscriptionBilling: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  toggleToolStatus: TypedContractMethod<
    [toolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  toolLicenseNFT: TypedContractMethod<[], [string], "view">;

  totalToolsListed: TypedContractMethod<[], [bigint], "view">;

  updatePlatformFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateUsdcToken: TypedContractMethod<
    [newUsdcToken: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_RATING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_RATING"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveTools"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getReviewCount"
  ): TypedContractMethod<[toolId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getToolListing"
  ): TypedContractMethod<
    [toolId: BigNumberish],
    [ToolMarketplace.ToolListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getToolReviews"
  ): TypedContractMethod<
    [toolId: BigNumberish],
    [ToolMarketplace.ReviewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _toolLicenseNFT: AddressLike,
      _revenueSplitter: AddressLike,
      _subscriptionBilling: AddressLike,
      _usdcToken: AddressLike,
      _admin: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "leaveReview"
  ): TypedContractMethod<
    [toolId: BigNumberish, rating: BigNumberish, comment: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listTool"
  ): TypedContractMethod<
    [
      name: string,
      category: string,
      monthlyPrice: BigNumberish,
      metadataURI: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, bigint, bigint, bigint] & {
        toolId: bigint;
        developer: string;
        isActive: boolean;
        totalSales: bigint;
        rating: bigint;
        reviewCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "platformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseLicense"
  ): TypedContractMethod<
    [toolId: BigNumberish, durationMonths: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revenueSplitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscriptionBilling"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "toggleToolStatus"
  ): TypedContractMethod<[toolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toolLicenseNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalToolsListed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePlatformFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateUsdcToken"
  ): TypedContractMethod<[newUsdcToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "LicensePurchased"
  ): TypedContractEvent<
    LicensePurchasedEvent.InputTuple,
    LicensePurchasedEvent.OutputTuple,
    LicensePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ToolListed"
  ): TypedContractEvent<
    ToolListedEvent.InputTuple,
    ToolListedEvent.OutputTuple,
    ToolListedEvent.OutputObject
  >;
  getEvent(
    key: "ToolStatusUpdated"
  ): TypedContractEvent<
    ToolStatusUpdatedEvent.InputTuple,
    ToolStatusUpdatedEvent.OutputTuple,
    ToolStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "LicensePurchased(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LicensePurchasedEvent.InputTuple,
      LicensePurchasedEvent.OutputTuple,
      LicensePurchasedEvent.OutputObject
    >;
    LicensePurchased: TypedContractEvent<
      LicensePurchasedEvent.InputTuple,
      LicensePurchasedEvent.OutputTuple,
      LicensePurchasedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "ReviewSubmitted(uint256,address,uint256,string,uint256)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ToolListed(uint256,address,string,string,uint256,uint256)": TypedContractEvent<
      ToolListedEvent.InputTuple,
      ToolListedEvent.OutputTuple,
      ToolListedEvent.OutputObject
    >;
    ToolListed: TypedContractEvent<
      ToolListedEvent.InputTuple,
      ToolListedEvent.OutputTuple,
      ToolListedEvent.OutputObject
    >;

    "ToolStatusUpdated(uint256,bool,uint256)": TypedContractEvent<
      ToolStatusUpdatedEvent.InputTuple,
      ToolStatusUpdatedEvent.OutputTuple,
      ToolStatusUpdatedEvent.OutputObject
    >;
    ToolStatusUpdated: TypedContractEvent<
      ToolStatusUpdatedEvent.InputTuple,
      ToolStatusUpdatedEvent.OutputTuple,
      ToolStatusUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
