"""Initial schema with marketplace, purchases, and user settings

Revision ID: 73e5589972b4
Revises: 
Create Date: 2025-11-20 15:23:21.505898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e5589972b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_wallet_address'), 'api_keys', ['wallet_address'], unique=False)
    op.create_table('marketplace_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_categories_id'), 'marketplace_categories', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_categories_name'), 'marketplace_categories', ['name'], unique=True)
    op.create_index(op.f('ix_marketplace_categories_slug'), 'marketplace_categories', ['slug'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('ui_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_wallet_address'), 'user_settings', ['wallet_address'], unique=True)
    op.create_table('marketplace_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('has_adapter', sa.Boolean(), nullable=True),
    sa.Column('storage_info', sa.Text(), nullable=True),
    sa.Column('pricing_model', sa.Enum('FIXED_TIER', 'PER_USER', 'PER_SEAT', 'USAGE_BASED', 'CONTACT_BASED', 'HYBRID', name='pricingmodel'), nullable=True),
    sa.Column('transaction_fee_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('transaction_fee_fixed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('per_unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('coming_soon', sa.Boolean(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('support_url', sa.String(length=500), nullable=True),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['marketplace_categories.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_category_active', 'marketplace_products', ['category', 'active'], unique=False)
    op.create_index(op.f('ix_marketplace_products_active'), 'marketplace_products', ['active'], unique=False)
    op.create_index(op.f('ix_marketplace_products_category'), 'marketplace_products', ['category'], unique=False)
    op.create_index(op.f('ix_marketplace_products_featured'), 'marketplace_products', ['featured'], unique=False)
    op.create_index(op.f('ix_marketplace_products_id'), 'marketplace_products', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_products_name'), 'marketplace_products', ['name'], unique=False)
    op.create_index(op.f('ix_marketplace_products_slug'), 'marketplace_products', ['slug'], unique=True)
    op.create_table('marketplace_data_sync_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_data_sync_types_id'), 'marketplace_data_sync_types', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_data_sync_types_product_id'), 'marketplace_data_sync_types', ['product_id'], unique=False)
    op.create_table('marketplace_pricing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_discount_percent', sa.Integer(), nullable=True),
    sa.Column('is_per_user', sa.Boolean(), nullable=True),
    sa.Column('minimum_users', sa.Integer(), nullable=True),
    sa.Column('maximum_users', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('onboarding_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_product_tier', 'marketplace_pricing_plans', ['product_id', 'tier'], unique=False)
    op.create_index(op.f('ix_marketplace_pricing_plans_active'), 'marketplace_pricing_plans', ['active'], unique=False)
    op.create_index(op.f('ix_marketplace_pricing_plans_id'), 'marketplace_pricing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_pricing_plans_is_popular'), 'marketplace_pricing_plans', ['is_popular'], unique=False)
    op.create_index(op.f('ix_marketplace_pricing_plans_product_id'), 'marketplace_pricing_plans', ['product_id'], unique=False)
    op.create_index(op.f('ix_marketplace_pricing_plans_tier'), 'marketplace_pricing_plans', ['tier'], unique=False)
    op.create_table('marketplace_product_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('per_unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_per_user', sa.Boolean(), nullable=True),
    sa.Column('required_plan_tier', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_product_addons_id'), 'marketplace_product_addons', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_product_addons_product_id'), 'marketplace_product_addons', ['product_id'], unique=False)
    op.create_table('marketplace_plan_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('feature_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_included', sa.Boolean(), nullable=True),
    sa.Column('is_highlight', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['marketplace_pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_plan_sort', 'marketplace_plan_features', ['plan_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_marketplace_plan_features_id'), 'marketplace_plan_features', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_plan_features_plan_id'), 'marketplace_plan_features', ['plan_id'], unique=False)
    op.create_index(op.f('ix_marketplace_plan_features_product_id'), 'marketplace_plan_features', ['product_id'], unique=False)
    op.create_table('marketplace_plan_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('limit_key', sa.String(length=100), nullable=False),
    sa.Column('limit_value', sa.String(length=100), nullable=True),
    sa.Column('display_text', sa.String(length=255), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['marketplace_pricing_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_plan_limits_id'), 'marketplace_plan_limits', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_plan_limits_plan_id'), 'marketplace_plan_limits', ['plan_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pricing_plan_id', sa.Integer(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('license_nft_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['marketplace_pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash')
    )
    op.create_index('idx_purchase_date', 'purchases', ['purchase_date'], unique=False)
    op.create_index('idx_user_product', 'purchases', ['user_address', 'product_id'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_user_address'), 'purchases', ['user_address'], unique=False)
    op.create_table('integration_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('sync_frequency', sa.String(length=20), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=True),
    sa.Column('sync_invoices', sa.Boolean(), nullable=True),
    sa.Column('sync_customers', sa.Boolean(), nullable=True),
    sa.Column('sync_products', sa.Boolean(), nullable=True),
    sa.Column('sync_transactions', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_events', sa.JSON(), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_address', 'product_id', name='uq_user_product_config')
    )
    op.create_index(op.f('ix_integration_configs_id'), 'integration_configs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_configs_user_address'), 'integration_configs', ['user_address'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_address', 'provider', 'is_active', name='uq_user_provider_active')
    )
    op.create_index('idx_oauth_expires', 'oauth_tokens', ['expires_at'], unique=False)
    op.create_index('idx_oauth_provider', 'oauth_tokens', ['provider', 'is_active'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_id'), 'oauth_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_address'), 'oauth_tokens', ['user_address'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pricing_plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'TRIAL', 'CANCELLED', 'EXPIRED', 'SUSPENDED', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('current_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pricing_plan_id'], ['marketplace_pricing_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    op.create_index('idx_subscription_dates', 'subscriptions', ['current_period_end', 'next_billing_date'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_address'), 'subscriptions', ['user_address'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_address', sa.String(length=42), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('oauth_token_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'PARTIAL', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('last_sync_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sync_params', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['oauth_token_id'], ['oauth_tokens.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['marketplace_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_dates', 'sync_logs', ['started_at', 'completed_at'], unique=False)
    op.create_index('idx_sync_product', 'sync_logs', ['product_id', 'status'], unique=False)
    op.create_index('idx_sync_status', 'sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sync_logs_user_address'), 'sync_logs', ['user_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_user_address'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_index('idx_sync_status', table_name='sync_logs')
    op.drop_index('idx_sync_product', table_name='sync_logs')
    op.drop_index('idx_sync_dates', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_subscriptions_user_address'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_index('idx_subscription_dates', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_oauth_tokens_user_address'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_id'), table_name='oauth_tokens')
    op.drop_index('idx_oauth_provider', table_name='oauth_tokens')
    op.drop_index('idx_oauth_expires', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_integration_configs_user_address'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_purchases_user_address'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index('idx_user_product', table_name='purchases')
    op.drop_index('idx_purchase_date', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_marketplace_plan_limits_plan_id'), table_name='marketplace_plan_limits')
    op.drop_index(op.f('ix_marketplace_plan_limits_id'), table_name='marketplace_plan_limits')
    op.drop_table('marketplace_plan_limits')
    op.drop_index(op.f('ix_marketplace_plan_features_product_id'), table_name='marketplace_plan_features')
    op.drop_index(op.f('ix_marketplace_plan_features_plan_id'), table_name='marketplace_plan_features')
    op.drop_index(op.f('ix_marketplace_plan_features_id'), table_name='marketplace_plan_features')
    op.drop_index('idx_feature_plan_sort', table_name='marketplace_plan_features')
    op.drop_table('marketplace_plan_features')
    op.drop_index(op.f('ix_marketplace_product_addons_product_id'), table_name='marketplace_product_addons')
    op.drop_index(op.f('ix_marketplace_product_addons_id'), table_name='marketplace_product_addons')
    op.drop_table('marketplace_product_addons')
    op.drop_index(op.f('ix_marketplace_pricing_plans_tier'), table_name='marketplace_pricing_plans')
    op.drop_index(op.f('ix_marketplace_pricing_plans_product_id'), table_name='marketplace_pricing_plans')
    op.drop_index(op.f('ix_marketplace_pricing_plans_is_popular'), table_name='marketplace_pricing_plans')
    op.drop_index(op.f('ix_marketplace_pricing_plans_id'), table_name='marketplace_pricing_plans')
    op.drop_index(op.f('ix_marketplace_pricing_plans_active'), table_name='marketplace_pricing_plans')
    op.drop_index('idx_plan_product_tier', table_name='marketplace_pricing_plans')
    op.drop_table('marketplace_pricing_plans')
    op.drop_index(op.f('ix_marketplace_data_sync_types_product_id'), table_name='marketplace_data_sync_types')
    op.drop_index(op.f('ix_marketplace_data_sync_types_id'), table_name='marketplace_data_sync_types')
    op.drop_table('marketplace_data_sync_types')
    op.drop_index(op.f('ix_marketplace_products_slug'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_name'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_id'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_featured'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_category'), table_name='marketplace_products')
    op.drop_index(op.f('ix_marketplace_products_active'), table_name='marketplace_products')
    op.drop_index('idx_product_category_active', table_name='marketplace_products')
    op.drop_table('marketplace_products')
    op.drop_index(op.f('ix_user_settings_wallet_address'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_marketplace_categories_slug'), table_name='marketplace_categories')
    op.drop_index(op.f('ix_marketplace_categories_name'), table_name='marketplace_categories')
    op.drop_index(op.f('ix_marketplace_categories_id'), table_name='marketplace_categories')
    op.drop_table('marketplace_categories')
    op.drop_index(op.f('ix_api_keys_wallet_address'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
