#!/bin/bash

echo "========================================="
echo "Varity Generic Dashboard - Complete Demo"
echo "========================================="
echo ""
echo "This script demonstrates the complete user flow."
echo ""

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

# Demo mode check
INTERACTIVE=true
if [ "$1" == "--auto" ]; then
    INTERACTIVE=false
    echo "Running in automatic mode..."
    echo ""
fi

pause_demo() {
    if [ "$INTERACTIVE" = true ]; then
        read -p "Press Enter to continue..."
    else
        sleep 2
    fi
}

echo -e "${BLUE}Phase 1: Setup & Discovery${NC}"
echo "------------------------------------"
echo "1. User visits: http://localhost:3001"
echo "2. Homepage displays:"
echo "   • Hero section: 'AI-Powered Business Dashboard'"
echo "   • Feature cards: QuickBooks, Salesforce, Analytics"
echo "   • CTA: 'Connect Wallet to Get Started'"
echo "3. User sees: No login required to browse"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 2: Authentication${NC}"
echo "------------------------------------"
echo "4. User clicks 'Login' button in navbar"
echo "5. Privy modal appears with options:"
echo "   ✓ Email (magic link)"
echo "   ✓ Google (OAuth)"
echo "   ✓ Wallet (MetaMask, WalletConnect)"
echo "6. User selects authentication method"
echo "7. Privy creates embedded wallet automatically"
echo "8. User wallet address: 0xAbC...DeF"
echo ""
echo -e "${CYAN}Technical Flow:${NC}"
echo "   → Privy authenticates user"
echo "   → Embedded wallet created (EOA)"
echo "   → Session stored in localStorage"
echo "   → JWT token issued for API calls"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 3: Empty Dashboard State${NC}"
echo "------------------------------------"
echo "9. User redirected to /dashboard"
echo "10. Dashboard shows empty state:"
echo ""
echo "    ┌─────────────────────────────────────┐"
echo "    │ 🤖 AI Business Assistant            │"
echo "    ├─────────────────────────────────────┤"
echo "    │ No integrations connected yet.      │"
echo "    │                                     │"
echo "    │ Connect QuickBooks, Salesforce, or  │"
echo "    │ other tools to unlock AI insights.  │"
echo "    │                                     │"
echo "    │ [Browse Marketplace →]              │"
echo "    └─────────────────────────────────────┘"
echo ""
echo "11. Business Data section:"
echo "    • Revenue: --"
echo "    • Expenses: --"
echo "    • Profit: --"
echo "    • CTA: 'Install integrations to see data'"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 4: Marketplace Discovery${NC}"
echo "------------------------------------"
echo "12. User clicks 'Browse Marketplace →'"
echo "13. Navigates to /marketplace"
echo "14. Sees 8 integration cards:"
echo ""
echo "    ┌──────────────────┬──────────────────┬──────────────────┐"
echo "    │ QuickBooks       │ Salesforce       │ Shopify          │"
echo "    │ Accounting       │ CRM              │ E-commerce       │"
echo "    │ \$49/month        │ \$99/month        │ \$79/month        │"
echo "    │ [Install]        │ [Install]        │ [Install]        │"
echo "    └──────────────────┴──────────────────┴──────────────────┘"
echo ""
echo "    ┌──────────────────┬──────────────────┬──────────────────┐"
echo "    │ Monday.com       │ Stripe           │ Slack            │"
echo "    │ Project Mgmt     │ Payments         │ Communication    │"
echo "    │ \$45/month        │ Free             │ \$8/month         │"
echo "    │ [Install]        │ [Install]        │ [Install]        │"
echo "    └──────────────────┴──────────────────┴──────────────────┘"
echo ""
echo "    ┌──────────────────┬──────────────────┐"
echo "    │ HubSpot          │ Zendesk          │"
echo "    │ Marketing        │ Support          │"
echo "    │ \$120/month       │ \$89/month        │"
echo "    │ [Install]        │ [Install]        │"
echo "    └──────────────────┴──────────────────┘"
echo ""
echo "15. User can filter by:"
echo "    • Category (Accounting, CRM, etc.)"
echo "    • Price range"
echo "    • Featured tools"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 5: Tool Purchase (QuickBooks)${NC}"
echo "------------------------------------"
echo "16. User clicks 'Install' on QuickBooks card"
echo "17. Transaction modal appears:"
echo ""
echo "    ┌─────────────────────────────────────┐"
echo "    │ Install QuickBooks Integration      │"
echo "    ├─────────────────────────────────────┤"
echo "    │ Monthly Price: 49 USDC              │"
echo "    │ License Type: NFT (ERC-1155)        │"
echo "    │                                     │"
echo "    │ Transaction 1:                      │"
echo "    │ ☐ Approve USDC spending (49 USDC)  │"
echo "    │                                     │"
echo "    │ Transaction 2:                      │"
echo "    │ ☐ Purchase license NFT              │"
echo "    │                                     │"
echo "    │ [Confirm Purchase]                  │"
echo "    └─────────────────────────────────────┘"
echo ""
echo "18. User confirms transaction"
echo "19. Metamask prompts:"
echo "    a) Approve USDC: 49 USDC"
echo "    b) Purchase license: Gas ~\$0.50"
echo ""
echo -e "${CYAN}Blockchain Transaction:${NC}"
echo "   → USDC.approve(ToolMarketplace, 49e6)"
echo "   → ToolMarketplace.purchaseTool(0, USDC)"
echo "   → ToolLicenseNFT.mint(user, toolId=0, amount=1)"
echo "   → RevenueSplitter.split(49 USDC → Varity, Tool Provider)"
echo ""
echo "20. Transaction confirmed"
echo "21. NFT license #0 minted to wallet"
echo "22. Button changes: 'Install' → 'Installed ✓'"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 6: Automatic Data Sync${NC}"
echo "------------------------------------"
echo "23. Backend detects new license:"
echo "    • Event: ToolPurchased(user, toolId=0)"
echo "    • Triggers: POST /api/v1/integrations/quickbooks/sync"
echo ""
echo "24. QuickBooks Adapter activates:"
echo ""
echo -e "${CYAN}Sync Process:${NC}"
echo "   Step 1: Generate mock data"
echo "           • 12 invoices (\$47,320 total)"
echo "           • 8 expenses (\$28,450 total)"
echo "           • 5 customers"
echo "           • 3 vendors"
echo ""
echo "   Step 2: Encrypt with Lit Protocol"
echo "           • Access condition: wallet === user"
echo "           • Algorithm: AES-256-GCM"
echo "           • Key: Derived from Lit PKPs"
echo ""
echo "   Step 3: Upload to Filecoin"
echo "           Namespace: /company-0xAbC...DeF/integrations/quickbooks/"
echo "           Files:"
echo "           • invoices.enc (15 KB)"
echo "           • expenses.enc (8 KB)"
echo "           • customers.enc (3 KB)"
echo "           • summary.enc (2 KB)"
echo "           CID: bafybeig...xyz123"
echo ""
echo "   Step 4: Create RAG index"
echo "           • Extract text from encrypted data"
echo "           • Generate embeddings (384-dim)"
echo "           • Store in vector DB (pgvector)"
echo ""
echo "   Step 5: Update metadata"
echo "           • PostgreSQL: tools table"
echo "           • Installation status: active"
echo "           • Last sync: $(date)"
echo ""
echo "25. User sees notification:"
echo "    '✓ QuickBooks connected and synced'"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 7: View Business Data${NC}"
echo "------------------------------------"
echo "26. User returns to /dashboard"
echo "27. Business Data section now populated:"
echo ""
echo "    ┌─────────────────────────────────────┐"
echo "    │ 📊 Business Overview                │"
echo "    ├─────────────────────────────────────┤"
echo "    │ Total Revenue:    \$47,320           │"
echo "    │ Total Expenses:   \$28,450           │"
echo "    │ Profit Margin:    40%               │"
echo "    │                                     │"
echo "    │ Data Source: QuickBooks             │"
echo "    │ Last Updated: Just now              │"
echo "    └─────────────────────────────────────┘"
echo ""
echo "28. Recent Invoices:"
echo "    • Invoice #1245: Acme Corp - \$8,500"
echo "    • Invoice #1246: TechCo - \$6,200"
echo "    • Invoice #1247: StartupXYZ - \$4,800"
echo ""
echo "29. Recent Expenses:"
echo "    • Office Rent - \$3,500"
echo "    • Cloud Services - \$2,200"
echo "    • Marketing - \$1,800"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 8: AI Query - Simple${NC}"
echo "------------------------------------"
echo "30. User scrolls to AI Chat component"
echo "31. AI shows connected integrations:"
echo "    'Connected: QuickBooks ✓'"
echo ""
echo "32. User types: 'What is my total revenue?'"
echo ""
echo -e "${CYAN}AI Processing:${NC}"
echo "   Step 1: Receive query"
echo "           • User: 'What is my total revenue?'"
echo "           • Wallet: 0xAbC...DeF"
echo ""
echo "   Step 2: Retrieve data from Filecoin"
echo "           • CID: bafybeig...xyz123"
echo "           • File: invoices.enc"
echo ""
echo "   Step 3: Decrypt with Lit Protocol"
echo "           • Verify: user owns license NFT #0"
echo "           • Decrypt: AES-256-GCM"
echo "           • Data: 12 invoices"
echo ""
echo "   Step 4: Build RAG context"
echo "           • Query embedding: 'total revenue'"
echo "           • Vector search: top 5 similar docs"
echo "           • Context: All invoice data"
echo ""
echo "   Step 5: Query Ollama LLM"
echo "           • Model: llama3.2"
echo "           • Prompt: System + Context + User query"
echo "           • Temperature: 0.7"
echo ""
echo "   Step 6: Generate response"
echo ""
echo "33. AI responds:"
echo ""
echo "    ┌─────────────────────────────────────┐"
echo "    │ 🤖 AI Assistant                     │"
echo "    ├─────────────────────────────────────┤"
echo "    │ Your total revenue is \$47,320 from  │"
echo "    │ 12 invoices in QuickBooks.          │"
echo "    │                                     │"
echo "    │ Breakdown:                          │"
echo "    │ • Top customer: Acme Corp (\$8,500)  │"
echo "    │ • Average invoice: \$3,943           │"
echo "    │ • Paid: \$42,100 (89%)               │"
echo "    │ • Outstanding: \$5,220 (11%)         │"
echo "    │                                     │"
echo "    │ Sources:                            │"
echo "    │ ✓ QuickBooks > Invoices             │"
echo "    └─────────────────────────────────────┘"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 9: AI Query - Complex${NC}"
echo "------------------------------------"
echo "34. User asks: 'Compare my revenue vs expenses by month'"
echo ""
echo -e "${CYAN}AI Processing:${NC}"
echo "   → Retrieves invoices.enc (revenue)"
echo "   → Retrieves expenses.enc (expenses)"
echo "   → Groups by month"
echo "   → Calculates profit margins"
echo "   → Generates insights"
echo ""
echo "35. AI responds with table:"
echo ""
echo "    Month     | Revenue  | Expenses | Profit | Margin"
echo "    ----------|----------|----------|--------|-------"
echo "    January   | \$12,400  | \$8,200   | \$4,200 | 34%"
echo "    February  | \$15,800  | \$9,100   | \$6,700 | 42%"
echo "    March     | \$19,120  | \$11,150  | \$7,970 | 42%"
echo ""
echo "    💡 Insights:"
echo "    • Revenue growing 23% month-over-month"
echo "    • Expenses growing 16% month-over-month"
echo "    • Profit margin improving steadily"
echo "    • Recommendation: Consider expanding team"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 10: Multi-Integration (Future)${NC}"
echo "------------------------------------"
echo "36. User installs Salesforce CRM"
echo "37. Salesforce syncs pipeline data:"
echo "    • 24 opportunities"
echo "    • \$285,000 in pipeline"
echo "    • 8 deals closing this quarter"
echo ""
echo "38. User asks AI:"
echo "    'Show me revenue vs pipeline forecast'"
echo ""
echo "39. AI queries BOTH integrations:"
echo "    • QuickBooks: Historical revenue"
echo "    • Salesforce: Future pipeline"
echo ""
echo "40. AI responds with combined insights:"
echo ""
echo "    ┌─────────────────────────────────────┐"
echo "    │ Revenue vs Pipeline Analysis        │"
echo "    ├─────────────────────────────────────┤"
echo "    │ Past 3 months (QuickBooks):         │"
echo "    │ • Revenue: \$47,320                  │"
echo "    │ • Growth: 23% MoM                   │"
echo "    │                                     │"
echo "    │ Next 3 months (Salesforce):         │"
echo "    │ • Pipeline: \$285,000                │"
echo "    │ • Expected close: \$142,500 (50%)    │"
echo "    │                                     │"
echo "    │ 💡 Insight:                          │"
echo "    │ If you maintain 50% close rate,     │"
echo "    │ you'll 3x your revenue next quarter.│"
echo "    │                                     │"
echo "    │ Sources:                            │"
echo "    │ ✓ QuickBooks > Invoices             │"
echo "    │ ✓ Salesforce > Opportunities        │"
echo "    └─────────────────────────────────────┘"
echo ""
pause_demo

echo ""
echo -e "${BLUE}Phase 11: Privacy & Security${NC}"
echo "------------------------------------"
echo "41. User checks data storage:"
echo "    • All data encrypted with Lit Protocol"
echo "    • Stored on Filecoin (decentralized)"
echo "    • Only user's wallet can decrypt"
echo "    • No cloud provider has access"
echo ""
echo "42. Storage architecture:"
echo ""
echo "    Layer 1: Encryption at Rest"
echo "             ↓ Lit Protocol AES-256-GCM"
echo ""
echo "    Layer 2: Distributed Storage"
echo "             ↓ Filecoin/IPFS"
echo ""
echo "    Layer 3: Data Availability"
echo "             ↓ Celestia DA + ZK proofs"
echo ""
echo "    Layer 4: Decentralized Compute"
echo "             ↓ Ollama (local LLM)"
echo ""
echo "    Layer 5: Blockchain Settlement"
echo "             ↓ Arbitrum L3 → Arbitrum One → Ethereum"
echo ""
echo "43. Privacy guarantees:"
echo "    ✓ No corporate surveillance"
echo "    ✓ No data mining for ads"
echo "    ✓ User owns encryption keys"
echo "    ✓ Immutable audit trail"
echo ""
pause_demo

echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}Demo Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo -e "${MAGENTA}Value Proposition Demonstrated:${NC}"
echo ""
echo "✓ Unified dashboard for all business tools"
echo "✓ Sovereign data storage (Filecoin + Lit)"
echo "✓ AI chatbot with RAG across integrations"
echo "✓ Blockchain-based licensing (NFTs)"
echo "✓ Maximum privacy & security"
echo "✓ 90% cost savings vs cloud alternatives"
echo ""
echo -e "${CYAN}Technical Stack Showcased:${NC}"
echo ""
echo "Frontend:  Next.js + Privy + thirdweb"
echo "Backend:   FastAPI + PostgreSQL + Redis"
echo "AI:        Ollama (llama3.2) + RAG"
echo "Storage:   Filecoin + Lit Protocol"
echo "Blockchain: Arbitrum L3 + Smart Contracts"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "1. Deploy contracts: cd contracts && npm run deploy"
echo "2. Test with real wallet"
echo "3. Integrate real QuickBooks OAuth"
echo "4. Add more integrations (Salesforce, etc.)"
echo "5. Deploy to Arbitrum testnet"
echo ""
echo "For technical details: README.md"
echo "For deployment guide: DEPLOYMENT_CHECKLIST.md"
